# Generated by Django 3.2.9 on 2021-11-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=255)),
                ('sustentavel', models.CharField(choices=[(1, 'Não sustentável'), (2, 'Sustentável')], max_length=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
