# Generated by Django 3.2.9 on 2021-11-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='sustentavel',
            field=models.CharField(choices=[('0', 'Não sustentável'), ('1', 'Sustentável')], max_length=1),
        ),
    ]
