# Generated by Django 3.2.9 on 2021-11-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenters', '0002_auto_20211105_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='setor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
