# Generated by Django 3.2.9 on 2021-11-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenters', '0003_datacenter_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='consumo_eletrico',
            field=models.IntegerField(default=0),
        ),
    ]
